dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.69.1-dev
  otelcol_version: 0.69.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.69.1
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.69.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.69.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.69.1
extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.69.1
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.69.1
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.69.1
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.69.1

